/* Generated By:JavaCC: Do not edit this line. AINLConstants.java */
package my.newLang;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AINLConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PLUS = 5;
  /** RegularExpression Id. */
  int MULTIPLY = 6;
  /** RegularExpression Id. */
  int IPLUA = 7;
  /** RegularExpression Id. */
  int IMINUS = 8;
  /** RegularExpression Id. */
  int IMULTIPLAY = 9;
  /** RegularExpression Id. */
  int IDIVIDE = 10;
  /** RegularExpression Id. */
  int POWER = 11;
  /** RegularExpression Id. */
  int PERCENT = 12;
  /** RegularExpression Id. */
  int IPERCENT = 13;
  /** RegularExpression Id. */
  int COMPR = 14;
  /** RegularExpression Id. */
  int LOGICCOMPR = 15;
  /** RegularExpression Id. */
  int NUM = 16;
  /** RegularExpression Id. */
  int LP = 17;
  /** RegularExpression Id. */
  int RP = 18;
  /** RegularExpression Id. */
  int DEF = 19;
  /** RegularExpression Id. */
  int KEY = 20;
  /** RegularExpression Id. */
  int READ = 21;
  /** RegularExpression Id. */
  int COUT = 22;
  /** RegularExpression Id. */
  int WRITE = 23;
  /** RegularExpression Id. */
  int ASSIGN = 24;
  /** RegularExpression Id. */
  int IF = 25;
  /** RegularExpression Id. */
  int ELSE = 26;
  /** RegularExpression Id. */
  int END = 27;
  /** RegularExpression Id. */
  int FOR = 28;
  /** RegularExpression Id. */
  int ENDFOR = 29;
  /** RegularExpression Id. */
  int FUNC = 30;
  /** RegularExpression Id. */
  int LOOP = 31;
  /** RegularExpression Id. */
  int SIMCOL = 32;
  /** RegularExpression Id. */
  int WHILE = 33;
  /** RegularExpression Id. */
  int COLON = 34;
  /** RegularExpression Id. */
  int RETURN = 35;
  /** RegularExpression Id. */
  int COMA = 36;
  /** RegularExpression Id. */
  int PRO = 37;
  /** RegularExpression Id. */
  int ID = 38;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<PLUS>",
    "<MULTIPLY>",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"^\"",
    "\"%\"",
    "\"%=\"",
    "<COMPR>",
    "<LOGICCOMPR>",
    "<NUM>",
    "\"(\"",
    "\")\"",
    "\"def\"",
    "<KEY>",
    "\"->\"",
    "\"\\\"\"",
    "\"<-\"",
    "\":=\"",
    "\"?\"",
    "\"??\"",
    "\"!\"",
    "\"&\"",
    "\"END\"",
    "\"func\"",
    "\"-->\"",
    "\";\"",
    "\"@\"",
    "\":\"",
    "\"return\"",
    "\",\"",
    "\"_\"",
    "<ID>",
  };

}
